### ISSUE TITLE
Variable port

### ISSUE THREAD

**Issue by cugu** [LukasMarckmiller/RemoteDataAcquisitionSystem#14]
Would be nice to be able to change the port. e.g. router.Run(os.Getenv("PORT"))

8000 can be default.

Requires changes in HTTPClient.js:
```js
const HTTP = axios.create({
    baseURL: "/",
});
```

and CustomStepper.vue:
```js
axios.get('/image/' [...]
```

**Comment by LukasMarckmiller** [comment]
Not possible for JS to get Environment Variables. Use a Config File instead which is used by front and backend

**Comment by cugu** [comment]
If you use relative urls you do not need environment vars.
