### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by cugu** [LukasMarckmiller/RemoteDataAcquisitionSystem#15]
Suggestion:

Create Makefile:
```make
init:
	git submodule update --init --recursive
	cd RemoteForensicApplianceFrontend && yarn run build %% cd -
run:
	go run .
````

**Comment by LukasMarckmiller** [comment]
https://github.com/gobuffalo/packr 

func main() {
  box := packr.NewBox("./web")

  http.Handle("/", http.FileServer(box)) //Require Gin Code for the route mapping to file server
  http.ListenAndServe(":3000", nil)
}
